/**
 * generated by Xtext 2.12.0
 */
package org.xtext.behaviortree.scoping;

import org.xtext.behaviortree.scoping.AbstractBehaviorTreeScopeProvider;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
@SuppressWarnings("all")
public class BehaviorTreeScopeProvider extends AbstractBehaviorTreeScopeProvider {
}
