/**
 * generated by Xtext 2.12.0
 */
package org.xtext.miron.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;
import org.xtext.miron.ui.AbstractMIRoNUiModule;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class MIRoNUiModule extends AbstractMIRoNUiModule {
  public MIRoNUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
