/*
 * generated by Xtext 2.16.0
 */
package org.xtext.behaviortree.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractBehaviorTreeScopeProvider extends DelegatingScopeProvider {
}
