/*
 * generated by Xtext 2.12.0
 */
package org.xtext.miron.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.CrossReference;
import org.eclipse.xtext.EnumLiteralDeclaration;
import org.eclipse.xtext.EnumRule;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder.AbstractEnumRuleElementFinder;
import org.eclipse.xtext.service.AbstractElementFinder.AbstractGrammarElementFinder;
import org.eclipse.xtext.service.GrammarProvider;
import org.xtext.roqme.services.RoQMEGrammarAccess;

@Singleton
public class MIRoNGrammarAccess extends AbstractGrammarElementFinder {
	
	public class MironModelElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.miron.MIRoN.MironModel");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Group cGroup_0 = (Group)cGroup.eContents().get(0);
		private final Assignment cDescriptionAssignment_0_0 = (Assignment)cGroup_0.eContents().get(0);
		private final RuleCall cDescriptionElementDescriptionParserRuleCall_0_0_0 = (RuleCall)cDescriptionAssignment_0_0.eContents().get(0);
		private final Keyword cMironKeyword_0_1 = (Keyword)cGroup_0.eContents().get(1);
		private final Assignment cNamespaceAssignment_0_2 = (Assignment)cGroup_0.eContents().get(2);
		private final RuleCall cNamespaceEStringParserRuleCall_0_2_0 = (RuleCall)cNamespaceAssignment_0_2.eContents().get(0);
		private final Assignment cSentencesAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cSentencesImportParserRuleCall_1_0 = (RuleCall)cSentencesAssignment_1.eContents().get(0);
		private final Alternatives cAlternatives_2 = (Alternatives)cGroup.eContents().get(2);
		private final Assignment cDataTypesAssignment_2_0 = (Assignment)cAlternatives_2.eContents().get(0);
		private final RuleCall cDataTypesDataTypeDefinitionParserRuleCall_2_0_0 = (RuleCall)cDataTypesAssignment_2_0.eContents().get(0);
		private final Assignment cVariablesAssignment_2_1 = (Assignment)cAlternatives_2.eContents().get(1);
		private final RuleCall cVariablesTypedVariableParserRuleCall_2_1_0 = (RuleCall)cVariablesAssignment_2_1.eContents().get(0);
		private final Assignment cSentencesAssignment_2_2 = (Assignment)cAlternatives_2.eContents().get(2);
		private final RuleCall cSentencesSentenceParserRuleCall_2_2_0 = (RuleCall)cSentencesAssignment_2_2.eContents().get(0);
		
		//MironModel mirondatatypes::MironModel:
		//	(description=ElementDescription? 'miron' namespace=EString)?
		//	sentences+=Import* (dataTypes+=DataTypeDefinition
		//	| variables+=TypedVariable
		//	| sentences+=Sentence)*;
		@Override public ParserRule getRule() { return rule; }
		
		//(description=ElementDescription? 'miron' namespace=EString)? sentences+=Import* (dataTypes+=DataTypeDefinition |
		//variables+=TypedVariable | sentences+=Sentence)*
		public Group getGroup() { return cGroup; }
		
		//(description=ElementDescription? 'miron' namespace=EString)?
		public Group getGroup_0() { return cGroup_0; }
		
		//description=ElementDescription?
		public Assignment getDescriptionAssignment_0_0() { return cDescriptionAssignment_0_0; }
		
		//ElementDescription
		public RuleCall getDescriptionElementDescriptionParserRuleCall_0_0_0() { return cDescriptionElementDescriptionParserRuleCall_0_0_0; }
		
		//'miron'
		public Keyword getMironKeyword_0_1() { return cMironKeyword_0_1; }
		
		//namespace=EString
		public Assignment getNamespaceAssignment_0_2() { return cNamespaceAssignment_0_2; }
		
		//EString
		public RuleCall getNamespaceEStringParserRuleCall_0_2_0() { return cNamespaceEStringParserRuleCall_0_2_0; }
		
		//sentences+=Import*
		public Assignment getSentencesAssignment_1() { return cSentencesAssignment_1; }
		
		//Import
		public RuleCall getSentencesImportParserRuleCall_1_0() { return cSentencesImportParserRuleCall_1_0; }
		
		//(dataTypes+=DataTypeDefinition | variables+=TypedVariable | sentences+=Sentence)*
		public Alternatives getAlternatives_2() { return cAlternatives_2; }
		
		//dataTypes+=DataTypeDefinition
		public Assignment getDataTypesAssignment_2_0() { return cDataTypesAssignment_2_0; }
		
		//DataTypeDefinition
		public RuleCall getDataTypesDataTypeDefinitionParserRuleCall_2_0_0() { return cDataTypesDataTypeDefinitionParserRuleCall_2_0_0; }
		
		//variables+=TypedVariable
		public Assignment getVariablesAssignment_2_1() { return cVariablesAssignment_2_1; }
		
		//TypedVariable
		public RuleCall getVariablesTypedVariableParserRuleCall_2_1_0() { return cVariablesTypedVariableParserRuleCall_2_1_0; }
		
		//sentences+=Sentence
		public Assignment getSentencesAssignment_2_2() { return cSentencesAssignment_2_2; }
		
		//Sentence
		public RuleCall getSentencesSentenceParserRuleCall_2_2_0() { return cSentencesSentenceParserRuleCall_2_2_0; }
	}
	public class ImportElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.miron.MIRoN.Import");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cImportKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cImportURIAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cImportURIEStringParserRuleCall_1_0 = (RuleCall)cImportURIAssignment_1.eContents().get(0);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final Keyword cAsKeyword_2_0 = (Keyword)cGroup_2.eContents().get(0);
		private final Assignment cAliasAssignment_2_1 = (Assignment)cGroup_2.eContents().get(1);
		private final RuleCall cAliasEStringParserRuleCall_2_1_0 = (RuleCall)cAliasAssignment_2_1.eContents().get(0);
		
		//@ Override Import mironkernel::Import:
		//	'import' importURI=EString ('as' alias=EString)?;
		@Override public ParserRule getRule() { return rule; }
		
		//'import' importURI=EString ('as' alias=EString)?
		public Group getGroup() { return cGroup; }
		
		//'import'
		public Keyword getImportKeyword_0() { return cImportKeyword_0; }
		
		//importURI=EString
		public Assignment getImportURIAssignment_1() { return cImportURIAssignment_1; }
		
		//EString
		public RuleCall getImportURIEStringParserRuleCall_1_0() { return cImportURIEStringParserRuleCall_1_0; }
		
		//('as' alias=EString)?
		public Group getGroup_2() { return cGroup_2; }
		
		//'as'
		public Keyword getAsKeyword_2_0() { return cAsKeyword_2_0; }
		
		//alias=EString
		public Assignment getAliasAssignment_2_1() { return cAliasAssignment_2_1; }
		
		//EString
		public RuleCall getAliasEStringParserRuleCall_2_1_0() { return cAliasEStringParserRuleCall_2_1_0; }
	}
	public class EnumTypeElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.miron.MIRoN.EnumType");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cEnumKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Keyword cLeftSquareBracketKeyword_1_0 = (Keyword)cGroup_1.eContents().get(0);
		private final Assignment cCardinalityAssignment_1_1 = (Assignment)cGroup_1.eContents().get(1);
		private final RuleCall cCardinalityINTTerminalRuleCall_1_1_0 = (RuleCall)cCardinalityAssignment_1_1.eContents().get(0);
		private final Keyword cRightSquareBracketKeyword_1_2 = (Keyword)cGroup_1.eContents().get(2);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cLiteralsAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cLiteralsEnumLiteralAuxParserRuleCall_3_0 = (RuleCall)cLiteralsAssignment_3.eContents().get(0);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cCommaKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cLiteralsAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cLiteralsEnumLiteralAuxParserRuleCall_4_1_0 = (RuleCall)cLiteralsAssignment_4_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//@ Override EnumType roqmedatatypes::EnumType:
		//	'enum' ('[' cardinality=INT ']')?
		//	'{'
		//	literals+=EnumLiteralAux (',' literals+=EnumLiteralAux)*
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//'enum' ('[' cardinality=INT ']')? '{' literals+=EnumLiteralAux (',' literals+=EnumLiteralAux)* '}'
		public Group getGroup() { return cGroup; }
		
		//'enum'
		public Keyword getEnumKeyword_0() { return cEnumKeyword_0; }
		
		//('[' cardinality=INT ']')?
		public Group getGroup_1() { return cGroup_1; }
		
		//'['
		public Keyword getLeftSquareBracketKeyword_1_0() { return cLeftSquareBracketKeyword_1_0; }
		
		//cardinality=INT
		public Assignment getCardinalityAssignment_1_1() { return cCardinalityAssignment_1_1; }
		
		//INT
		public RuleCall getCardinalityINTTerminalRuleCall_1_1_0() { return cCardinalityINTTerminalRuleCall_1_1_0; }
		
		//']'
		public Keyword getRightSquareBracketKeyword_1_2() { return cRightSquareBracketKeyword_1_2; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//literals+=EnumLiteralAux
		public Assignment getLiteralsAssignment_3() { return cLiteralsAssignment_3; }
		
		//EnumLiteralAux
		public RuleCall getLiteralsEnumLiteralAuxParserRuleCall_3_0() { return cLiteralsEnumLiteralAuxParserRuleCall_3_0; }
		
		//(',' literals+=EnumLiteralAux)*
		public Group getGroup_4() { return cGroup_4; }
		
		//','
		public Keyword getCommaKeyword_4_0() { return cCommaKeyword_4_0; }
		
		//literals+=EnumLiteralAux
		public Assignment getLiteralsAssignment_4_1() { return cLiteralsAssignment_4_1; }
		
		//EnumLiteralAux
		public RuleCall getLiteralsEnumLiteralAuxParserRuleCall_4_1_0() { return cLiteralsEnumLiteralAuxParserRuleCall_4_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
	}
	public class EnumLiteralAuxElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.miron.MIRoN.EnumLiteralAux");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cEnumLiteralParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cBehaviorTreeLiteralParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//EnumLiteralAux roqmedatatypes::EnumLiteral:
		//	EnumLiteral | BehaviorTreeLiteral;
		@Override public ParserRule getRule() { return rule; }
		
		//EnumLiteral | BehaviorTreeLiteral
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//EnumLiteral
		public RuleCall getEnumLiteralParserRuleCall_0() { return cEnumLiteralParserRuleCall_0; }
		
		//BehaviorTreeLiteral
		public RuleCall getBehaviorTreeLiteralParserRuleCall_1() { return cBehaviorTreeLiteralParserRuleCall_1; }
	}
	public class BehaviorTreeLiteralElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.miron.MIRoN.BehaviorTreeLiteral");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cBehaviorTreeLiteralAction_0 = (Action)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cColonKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cReferenceAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final CrossReference cReferenceBehaviorTreeCrossReference_3_0 = (CrossReference)cReferenceAssignment_3.eContents().get(0);
		private final RuleCall cReferenceBehaviorTreeEStringParserRuleCall_3_0_1 = (RuleCall)cReferenceBehaviorTreeCrossReference_3_0.eContents().get(1);
		
		//BehaviorTreeLiteral roqmedatatypes::EnumLiteral:
		//	{mirondatatypes::BehaviorTreeLiteral} name=ID ":" reference=[behaviortree::BehaviorTree|EString];
		@Override public ParserRule getRule() { return rule; }
		
		//{mirondatatypes::BehaviorTreeLiteral} name=ID ":" reference=[behaviortree::BehaviorTree|EString]
		public Group getGroup() { return cGroup; }
		
		//{mirondatatypes::BehaviorTreeLiteral}
		public Action getBehaviorTreeLiteralAction_0() { return cBehaviorTreeLiteralAction_0; }
		
		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
		
		//":"
		public Keyword getColonKeyword_2() { return cColonKeyword_2; }
		
		//reference=[behaviortree::BehaviorTree|EString]
		public Assignment getReferenceAssignment_3() { return cReferenceAssignment_3; }
		
		//[behaviortree::BehaviorTree|EString]
		public CrossReference getReferenceBehaviorTreeCrossReference_3_0() { return cReferenceBehaviorTreeCrossReference_3_0; }
		
		//EString
		public RuleCall getReferenceBehaviorTreeEStringParserRuleCall_3_0_1() { return cReferenceBehaviorTreeEStringParserRuleCall_3_0_1; }
	}
	public class TypedVariableElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.miron.MIRoN.TypedVariable");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cParameterParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cTimerParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cGeneralPurposeVariableParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		private final RuleCall cContextParserRuleCall_3 = (RuleCall)cAlternatives.eContents().get(3);
		private final RuleCall cBeliefVariableParserRuleCall_4 = (RuleCall)cAlternatives.eContents().get(4);
		private final RuleCall cVariationPointParserRuleCall_5 = (RuleCall)cAlternatives.eContents().get(5);
		
		//@ Override TypedVariable roqmedatatypes::TypedVariable:
		//	Parameter | Timer | GeneralPurposeVariable | Context | BeliefVariable | VariationPoint;
		@Override public ParserRule getRule() { return rule; }
		
		//Parameter | Timer | GeneralPurposeVariable | Context | BeliefVariable | VariationPoint
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//Parameter
		public RuleCall getParameterParserRuleCall_0() { return cParameterParserRuleCall_0; }
		
		//Timer
		public RuleCall getTimerParserRuleCall_1() { return cTimerParserRuleCall_1; }
		
		//GeneralPurposeVariable
		public RuleCall getGeneralPurposeVariableParserRuleCall_2() { return cGeneralPurposeVariableParserRuleCall_2; }
		
		//Context
		public RuleCall getContextParserRuleCall_3() { return cContextParserRuleCall_3; }
		
		//BeliefVariable
		public RuleCall getBeliefVariableParserRuleCall_4() { return cBeliefVariableParserRuleCall_4; }
		
		//VariationPoint
		public RuleCall getVariationPointParserRuleCall_5() { return cVariationPointParserRuleCall_5; }
	}
	public class VariationPointElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.miron.MIRoN.VariationPoint");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cVarpointKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cColonKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cDeclarationAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cDeclarationDataTypeDeclarationParserRuleCall_3_0 = (RuleCall)cDeclarationAssignment_3.eContents().get(0);
		private final Assignment cBindingAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cBindingBindingParserRuleCall_4_0 = (RuleCall)cBindingAssignment_4.eContents().get(0);
		
		//VariationPoint mironkernel::VariationPoint:
		//	'varpoint' name=ID ':' declaration=DataTypeDeclaration
		//	binding=Binding;
		@Override public ParserRule getRule() { return rule; }
		
		//'varpoint' name=ID ':' declaration=DataTypeDeclaration binding=Binding
		public Group getGroup() { return cGroup; }
		
		//'varpoint'
		public Keyword getVarpointKeyword_0() { return cVarpointKeyword_0; }
		
		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
		
		//':'
		public Keyword getColonKeyword_2() { return cColonKeyword_2; }
		
		//declaration=DataTypeDeclaration
		public Assignment getDeclarationAssignment_3() { return cDeclarationAssignment_3; }
		
		//DataTypeDeclaration
		public RuleCall getDeclarationDataTypeDeclarationParserRuleCall_3_0() { return cDeclarationDataTypeDeclarationParserRuleCall_3_0; }
		
		//binding=Binding
		public Assignment getBindingAssignment_4() { return cBindingAssignment_4; }
		
		//Binding
		public RuleCall getBindingBindingParserRuleCall_4_0() { return cBindingBindingParserRuleCall_4_0; }
	}
	public class BindingElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.miron.MIRoN.Binding");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cInsertionTypeAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cInsertionTypeInsertionTypeEnumEnumRuleCall_0_0 = (RuleCall)cInsertionTypeAssignment_0.eContents().get(0);
		private final Alternatives cAlternatives_1 = (Alternatives)cGroup.eContents().get(1);
		private final Group cGroup_1_0 = (Group)cAlternatives_1.eContents().get(0);
		private final Keyword cXpathKeyword_1_0_0 = (Keyword)cGroup_1_0.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_1_0_1 = (Keyword)cGroup_1_0.eContents().get(1);
		private final Assignment cXpathAssignment_1_0_2 = (Assignment)cGroup_1_0.eContents().get(2);
		private final RuleCall cXpathEStringParserRuleCall_1_0_2_0 = (RuleCall)cXpathAssignment_1_0_2.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_1_0_3 = (Keyword)cGroup_1_0.eContents().get(3);
		private final Group cGroup_1_1 = (Group)cAlternatives_1.eContents().get(1);
		private final Assignment cTargetsAssignment_1_1_0 = (Assignment)cGroup_1_1.eContents().get(0);
		private final CrossReference cTargetsEObjectCrossReference_1_1_0_0 = (CrossReference)cTargetsAssignment_1_1_0.eContents().get(0);
		private final RuleCall cTargetsEObjectEStringParserRuleCall_1_1_0_0_1 = (RuleCall)cTargetsEObjectCrossReference_1_1_0_0.eContents().get(1);
		private final Group cGroup_1_1_1 = (Group)cGroup_1_1.eContents().get(1);
		private final Keyword cCommaKeyword_1_1_1_0 = (Keyword)cGroup_1_1_1.eContents().get(0);
		private final Assignment cTargetsAssignment_1_1_1_1 = (Assignment)cGroup_1_1_1.eContents().get(1);
		private final CrossReference cTargetsEObjectCrossReference_1_1_1_1_0 = (CrossReference)cTargetsAssignment_1_1_1_1.eContents().get(0);
		private final RuleCall cTargetsEObjectEStringParserRuleCall_1_1_1_1_0_1 = (RuleCall)cTargetsEObjectCrossReference_1_1_1_1_0.eContents().get(1);
		
		//Binding mironkernel::Binding:
		//	insertionType=InsertionTypeEnum ('xpath' '(' xpath=EString ')' | targets+=[ecore::EObject|EString] (','
		//	targets+=[ecore::EObject|EString])*);
		@Override public ParserRule getRule() { return rule; }
		
		//insertionType=InsertionTypeEnum ('xpath' '(' xpath=EString ')' | targets+=[ecore::EObject|EString] (','
		//targets+=[ecore::EObject|EString])*)
		public Group getGroup() { return cGroup; }
		
		//insertionType=InsertionTypeEnum
		public Assignment getInsertionTypeAssignment_0() { return cInsertionTypeAssignment_0; }
		
		//InsertionTypeEnum
		public RuleCall getInsertionTypeInsertionTypeEnumEnumRuleCall_0_0() { return cInsertionTypeInsertionTypeEnumEnumRuleCall_0_0; }
		
		//'xpath' '(' xpath=EString ')' | targets+=[ecore::EObject|EString] (',' targets+=[ecore::EObject|EString])*
		public Alternatives getAlternatives_1() { return cAlternatives_1; }
		
		//'xpath' '(' xpath=EString ')'
		public Group getGroup_1_0() { return cGroup_1_0; }
		
		//'xpath'
		public Keyword getXpathKeyword_1_0_0() { return cXpathKeyword_1_0_0; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_1_0_1() { return cLeftParenthesisKeyword_1_0_1; }
		
		//xpath=EString
		public Assignment getXpathAssignment_1_0_2() { return cXpathAssignment_1_0_2; }
		
		//EString
		public RuleCall getXpathEStringParserRuleCall_1_0_2_0() { return cXpathEStringParserRuleCall_1_0_2_0; }
		
		//')'
		public Keyword getRightParenthesisKeyword_1_0_3() { return cRightParenthesisKeyword_1_0_3; }
		
		//targets+=[ecore::EObject|EString] (',' targets+=[ecore::EObject|EString])*
		public Group getGroup_1_1() { return cGroup_1_1; }
		
		//targets+=[ecore::EObject|EString]
		public Assignment getTargetsAssignment_1_1_0() { return cTargetsAssignment_1_1_0; }
		
		//[ecore::EObject|EString]
		public CrossReference getTargetsEObjectCrossReference_1_1_0_0() { return cTargetsEObjectCrossReference_1_1_0_0; }
		
		//EString
		public RuleCall getTargetsEObjectEStringParserRuleCall_1_1_0_0_1() { return cTargetsEObjectEStringParserRuleCall_1_1_0_0_1; }
		
		//(',' targets+=[ecore::EObject|EString])*
		public Group getGroup_1_1_1() { return cGroup_1_1_1; }
		
		//','
		public Keyword getCommaKeyword_1_1_1_0() { return cCommaKeyword_1_1_1_0; }
		
		//targets+=[ecore::EObject|EString]
		public Assignment getTargetsAssignment_1_1_1_1() { return cTargetsAssignment_1_1_1_1; }
		
		//[ecore::EObject|EString]
		public CrossReference getTargetsEObjectCrossReference_1_1_1_1_0() { return cTargetsEObjectCrossReference_1_1_1_1_0; }
		
		//EString
		public RuleCall getTargetsEObjectEStringParserRuleCall_1_1_1_1_0_1() { return cTargetsEObjectEStringParserRuleCall_1_1_1_1_0_1; }
	}
	public class SentenceElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.miron.MIRoN.Sentence");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cObservationParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cRuleParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//@ Override Sentence roqmedatatypes::Sentence:
		//	Observation | Rule;
		@Override public ParserRule getRule() { return rule; }
		
		//Observation | Rule
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//Observation
		public RuleCall getObservationParserRuleCall_0() { return cObservationParserRuleCall_0; }
		
		//Rule
		public RuleCall getRuleParserRuleCall_1() { return cRuleParserRuleCall_1; }
	}
	public class RuleElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.miron.MIRoN.Rule");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cRuleKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cColonKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cTriggerAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cTriggerContextPatternParserRuleCall_3_0 = (RuleCall)cTriggerAssignment_3.eContents().get(0);
		private final Keyword cImpliesKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Alternatives cAlternatives_5 = (Alternatives)cGroup.eContents().get(5);
		private final Assignment cActionsAssignment_5_0 = (Assignment)cAlternatives_5.eContents().get(0);
		private final RuleCall cActionsRuleActionParserRuleCall_5_0_0 = (RuleCall)cActionsAssignment_5_0.eContents().get(0);
		private final Group cGroup_5_1 = (Group)cAlternatives_5.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_5_1_0 = (Keyword)cGroup_5_1.eContents().get(0);
		private final Assignment cActionsAssignment_5_1_1 = (Assignment)cGroup_5_1.eContents().get(1);
		private final RuleCall cActionsRuleActionParserRuleCall_5_1_1_0 = (RuleCall)cActionsAssignment_5_1_1.eContents().get(0);
		private final Group cGroup_5_1_2 = (Group)cGroup_5_1.eContents().get(2);
		private final Keyword cCommaKeyword_5_1_2_0 = (Keyword)cGroup_5_1_2.eContents().get(0);
		private final Assignment cActionsAssignment_5_1_2_1 = (Assignment)cGroup_5_1_2.eContents().get(1);
		private final RuleCall cActionsRuleActionParserRuleCall_5_1_2_1_0 = (RuleCall)cActionsAssignment_5_1_2_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_5_1_3 = (Keyword)cGroup_5_1.eContents().get(3);
		
		//Rule mironkernel::Rule:
		//	'rule' name=ID ':' trigger=ContextPattern 'implies' (actions+=RuleAction | '{' actions+=RuleAction (','
		//	actions+=RuleAction)+ '}');
		@Override public ParserRule getRule() { return rule; }
		
		//'rule' name=ID ':' trigger=ContextPattern 'implies' (actions+=RuleAction | '{' actions+=RuleAction (','
		//actions+=RuleAction)+ '}')
		public Group getGroup() { return cGroup; }
		
		//'rule'
		public Keyword getRuleKeyword_0() { return cRuleKeyword_0; }
		
		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
		
		//':'
		public Keyword getColonKeyword_2() { return cColonKeyword_2; }
		
		//trigger=ContextPattern
		public Assignment getTriggerAssignment_3() { return cTriggerAssignment_3; }
		
		//ContextPattern
		public RuleCall getTriggerContextPatternParserRuleCall_3_0() { return cTriggerContextPatternParserRuleCall_3_0; }
		
		//'implies'
		public Keyword getImpliesKeyword_4() { return cImpliesKeyword_4; }
		
		//actions+=RuleAction | '{' actions+=RuleAction (',' actions+=RuleAction)+ '}'
		public Alternatives getAlternatives_5() { return cAlternatives_5; }
		
		//actions+=RuleAction
		public Assignment getActionsAssignment_5_0() { return cActionsAssignment_5_0; }
		
		//RuleAction
		public RuleCall getActionsRuleActionParserRuleCall_5_0_0() { return cActionsRuleActionParserRuleCall_5_0_0; }
		
		//'{' actions+=RuleAction (',' actions+=RuleAction)+ '}'
		public Group getGroup_5_1() { return cGroup_5_1; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_5_1_0() { return cLeftCurlyBracketKeyword_5_1_0; }
		
		//actions+=RuleAction
		public Assignment getActionsAssignment_5_1_1() { return cActionsAssignment_5_1_1; }
		
		//RuleAction
		public RuleCall getActionsRuleActionParserRuleCall_5_1_1_0() { return cActionsRuleActionParserRuleCall_5_1_1_0; }
		
		//(',' actions+=RuleAction)+
		public Group getGroup_5_1_2() { return cGroup_5_1_2; }
		
		//','
		public Keyword getCommaKeyword_5_1_2_0() { return cCommaKeyword_5_1_2_0; }
		
		//actions+=RuleAction
		public Assignment getActionsAssignment_5_1_2_1() { return cActionsAssignment_5_1_2_1; }
		
		//RuleAction
		public RuleCall getActionsRuleActionParserRuleCall_5_1_2_1_0() { return cActionsRuleActionParserRuleCall_5_1_2_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_5_1_3() { return cRightCurlyBracketKeyword_5_1_3; }
	}
	public class RuleActionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.miron.MIRoN.RuleAction");
		private final RuleCall cVariantAssignmentParserRuleCall = (RuleCall)rule.eContents().get(1);
		
		//RuleAction mironkernel::RuleAction:
		//	VariantAssignment;
		@Override public ParserRule getRule() { return rule; }
		
		//VariantAssignment
		public RuleCall getVariantAssignmentParserRuleCall() { return cVariantAssignmentParserRuleCall; }
	}
	public class VariantAssignmentElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.miron.MIRoN.VariantAssignment");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cVariableAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final CrossReference cVariableVariationPointCrossReference_0_0 = (CrossReference)cVariableAssignment_0.eContents().get(0);
		private final RuleCall cVariableVariationPointQualifiedNameParserRuleCall_0_0_1 = (RuleCall)cVariableVariationPointCrossReference_0_0.eContents().get(1);
		private final Keyword cColonEqualsSignKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cValueAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cValueTypedValueParserRuleCall_2_0 = (RuleCall)cValueAssignment_2.eContents().get(0);
		
		//VariantAssignment mironkernel::VariantAssignment:
		//	variable=[mironkernel::VariationPoint|QualifiedName]
		//	':=' value=TypedValue;
		@Override public ParserRule getRule() { return rule; }
		
		//variable=[mironkernel::VariationPoint|QualifiedName] ':=' value=TypedValue
		public Group getGroup() { return cGroup; }
		
		//variable=[mironkernel::VariationPoint|QualifiedName]
		public Assignment getVariableAssignment_0() { return cVariableAssignment_0; }
		
		//[mironkernel::VariationPoint|QualifiedName]
		public CrossReference getVariableVariationPointCrossReference_0_0() { return cVariableVariationPointCrossReference_0_0; }
		
		//QualifiedName
		public RuleCall getVariableVariationPointQualifiedNameParserRuleCall_0_0_1() { return cVariableVariationPointQualifiedNameParserRuleCall_0_0_1; }
		
		//':='
		public Keyword getColonEqualsSignKeyword_1() { return cColonEqualsSignKeyword_1; }
		
		//value=TypedValue
		public Assignment getValueAssignment_2() { return cValueAssignment_2; }
		
		//TypedValue
		public RuleCall getValueTypedValueParserRuleCall_2_0() { return cValueTypedValueParserRuleCall_2_0; }
	}
	
	public class InsertionTypeEnumElements extends AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.miron.MIRoN.InsertionTypeEnum");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cINEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cINInKeyword_0_0 = (Keyword)cINEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cAFTEREnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cAFTERAfterKeyword_1_0 = (Keyword)cAFTEREnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cBEFOREEnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cBEFOREBeforeKeyword_2_0 = (Keyword)cBEFOREEnumLiteralDeclaration_2.eContents().get(0);
		
		//enum InsertionTypeEnum returns mironkernel::InsertionTypeEnum:
		//	IN='in' | AFTER='after' | BEFORE='before';
		public EnumRule getRule() { return rule; }
		
		//IN='in' | AFTER='after' | BEFORE='before'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//IN='in'
		public EnumLiteralDeclaration getINEnumLiteralDeclaration_0() { return cINEnumLiteralDeclaration_0; }
		
		//'in'
		public Keyword getINInKeyword_0_0() { return cINInKeyword_0_0; }
		
		//AFTER='after'
		public EnumLiteralDeclaration getAFTEREnumLiteralDeclaration_1() { return cAFTEREnumLiteralDeclaration_1; }
		
		//'after'
		public Keyword getAFTERAfterKeyword_1_0() { return cAFTERAfterKeyword_1_0; }
		
		//BEFORE='before'
		public EnumLiteralDeclaration getBEFOREEnumLiteralDeclaration_2() { return cBEFOREEnumLiteralDeclaration_2; }
		
		//'before'
		public Keyword getBEFOREBeforeKeyword_2_0() { return cBEFOREBeforeKeyword_2_0; }
	}
	
	private final MironModelElements pMironModel;
	private final ImportElements pImport;
	private final EnumTypeElements pEnumType;
	private final EnumLiteralAuxElements pEnumLiteralAux;
	private final BehaviorTreeLiteralElements pBehaviorTreeLiteral;
	private final TypedVariableElements pTypedVariable;
	private final VariationPointElements pVariationPoint;
	private final BindingElements pBinding;
	private final InsertionTypeEnumElements eInsertionTypeEnum;
	private final SentenceElements pSentence;
	private final RuleElements pRule;
	private final RuleActionElements pRuleAction;
	private final VariantAssignmentElements pVariantAssignment;
	
	private final Grammar grammar;
	
	private final RoQMEGrammarAccess gaRoQME;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public MIRoNGrammarAccess(GrammarProvider grammarProvider,
			RoQMEGrammarAccess gaRoQME,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaRoQME = gaRoQME;
		this.gaTerminals = gaTerminals;
		this.pMironModel = new MironModelElements();
		this.pImport = new ImportElements();
		this.pEnumType = new EnumTypeElements();
		this.pEnumLiteralAux = new EnumLiteralAuxElements();
		this.pBehaviorTreeLiteral = new BehaviorTreeLiteralElements();
		this.pTypedVariable = new TypedVariableElements();
		this.pVariationPoint = new VariationPointElements();
		this.pBinding = new BindingElements();
		this.eInsertionTypeEnum = new InsertionTypeEnumElements();
		this.pSentence = new SentenceElements();
		this.pRule = new RuleElements();
		this.pRuleAction = new RuleActionElements();
		this.pVariantAssignment = new VariantAssignmentElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("org.xtext.miron.MIRoN".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public RoQMEGrammarAccess getRoQMEGrammarAccess() {
		return gaRoQME;
	}
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//MironModel mirondatatypes::MironModel:
	//	(description=ElementDescription? 'miron' namespace=EString)?
	//	sentences+=Import* (dataTypes+=DataTypeDefinition
	//	| variables+=TypedVariable
	//	| sentences+=Sentence)*;
	public MironModelElements getMironModelAccess() {
		return pMironModel;
	}
	
	public ParserRule getMironModelRule() {
		return getMironModelAccess().getRule();
	}
	
	//@ Override Import mironkernel::Import:
	//	'import' importURI=EString ('as' alias=EString)?;
	public ImportElements getImportAccess() {
		return pImport;
	}
	
	public ParserRule getImportRule() {
		return getImportAccess().getRule();
	}
	
	//@ Override EnumType roqmedatatypes::EnumType:
	//	'enum' ('[' cardinality=INT ']')?
	//	'{'
	//	literals+=EnumLiteralAux (',' literals+=EnumLiteralAux)*
	//	'}';
	public EnumTypeElements getEnumTypeAccess() {
		return pEnumType;
	}
	
	public ParserRule getEnumTypeRule() {
		return getEnumTypeAccess().getRule();
	}
	
	//EnumLiteralAux roqmedatatypes::EnumLiteral:
	//	EnumLiteral | BehaviorTreeLiteral;
	public EnumLiteralAuxElements getEnumLiteralAuxAccess() {
		return pEnumLiteralAux;
	}
	
	public ParserRule getEnumLiteralAuxRule() {
		return getEnumLiteralAuxAccess().getRule();
	}
	
	//BehaviorTreeLiteral roqmedatatypes::EnumLiteral:
	//	{mirondatatypes::BehaviorTreeLiteral} name=ID ":" reference=[behaviortree::BehaviorTree|EString];
	public BehaviorTreeLiteralElements getBehaviorTreeLiteralAccess() {
		return pBehaviorTreeLiteral;
	}
	
	public ParserRule getBehaviorTreeLiteralRule() {
		return getBehaviorTreeLiteralAccess().getRule();
	}
	
	//@ Override TypedVariable roqmedatatypes::TypedVariable:
	//	Parameter | Timer | GeneralPurposeVariable | Context | BeliefVariable | VariationPoint;
	public TypedVariableElements getTypedVariableAccess() {
		return pTypedVariable;
	}
	
	public ParserRule getTypedVariableRule() {
		return getTypedVariableAccess().getRule();
	}
	
	//VariationPoint mironkernel::VariationPoint:
	//	'varpoint' name=ID ':' declaration=DataTypeDeclaration
	//	binding=Binding;
	public VariationPointElements getVariationPointAccess() {
		return pVariationPoint;
	}
	
	public ParserRule getVariationPointRule() {
		return getVariationPointAccess().getRule();
	}
	
	//Binding mironkernel::Binding:
	//	insertionType=InsertionTypeEnum ('xpath' '(' xpath=EString ')' | targets+=[ecore::EObject|EString] (','
	//	targets+=[ecore::EObject|EString])*);
	public BindingElements getBindingAccess() {
		return pBinding;
	}
	
	public ParserRule getBindingRule() {
		return getBindingAccess().getRule();
	}
	
	//enum InsertionTypeEnum returns mironkernel::InsertionTypeEnum:
	//	IN='in' | AFTER='after' | BEFORE='before';
	public InsertionTypeEnumElements getInsertionTypeEnumAccess() {
		return eInsertionTypeEnum;
	}
	
	public EnumRule getInsertionTypeEnumRule() {
		return getInsertionTypeEnumAccess().getRule();
	}
	
	//@ Override Sentence roqmedatatypes::Sentence:
	//	Observation | Rule;
	public SentenceElements getSentenceAccess() {
		return pSentence;
	}
	
	public ParserRule getSentenceRule() {
		return getSentenceAccess().getRule();
	}
	
	//Rule mironkernel::Rule:
	//	'rule' name=ID ':' trigger=ContextPattern 'implies' (actions+=RuleAction | '{' actions+=RuleAction (','
	//	actions+=RuleAction)+ '}');
	public RuleElements getRuleAccess() {
		return pRule;
	}
	
	public ParserRule getRuleRule() {
		return getRuleAccess().getRule();
	}
	
	//RuleAction mironkernel::RuleAction:
	//	VariantAssignment;
	public RuleActionElements getRuleActionAccess() {
		return pRuleAction;
	}
	
	public ParserRule getRuleActionRule() {
		return getRuleActionAccess().getRule();
	}
	
	//VariantAssignment mironkernel::VariantAssignment:
	//	variable=[mironkernel::VariationPoint|QualifiedName]
	//	':=' value=TypedValue;
	public VariantAssignmentElements getVariantAssignmentAccess() {
		return pVariantAssignment;
	}
	
	public ParserRule getVariantAssignmentRule() {
		return getVariantAssignmentAccess().getRule();
	}
	
	//RoqmeModel datatypes::RoqmeModel:
	//	(description=ElementDescription? 'roqme' namespace=EString)?
	//	sentences+=super::Import* (dataTypes+=DataTypeDefinition
	//	| variables+=super::TypedVariable
	//	| sentences+=super::Sentence)*;
	public RoQMEGrammarAccess.RoqmeModelElements getRoqmeModelAccess() {
		return gaRoQME.getRoqmeModelAccess();
	}
	
	public ParserRule getRoqmeModelRule() {
		return getRoqmeModelAccess().getRule();
	}
	
	//Context kernel::Context:
	//	DerivedContext | PrimitiveContext;
	public RoQMEGrammarAccess.ContextElements getContextAccess() {
		return gaRoQME.getContextAccess();
	}
	
	public ParserRule getContextRule() {
		return getContextAccess().getRule();
	}
	
	//PrimitiveContext kernel::PrimitiveContext:
	//	description=ElementDescription?
	//	'context' name=ID ':' declaration=DataTypeDeclaration;
	public RoQMEGrammarAccess.PrimitiveContextElements getPrimitiveContextAccess() {
		return gaRoQME.getPrimitiveContextAccess();
	}
	
	public ParserRule getPrimitiveContextRule() {
		return getPrimitiveContextAccess().getRule();
	}
	
	//DerivedContext kernel::DerivedContext:
	//	description=ElementDescription?
	//	'context' name=ID ':' declaration=DataTypeDeclaration
	//	':=' definition=ContextPattern;
	public RoQMEGrammarAccess.DerivedContextElements getDerivedContextAccess() {
		return gaRoQME.getDerivedContextAccess();
	}
	
	public ParserRule getDerivedContextRule() {
		return getDerivedContextAccess().getRule();
	}
	
	//GeneralPurposeVariable kernel::GeneralPurposeVariable:
	//	'var' name=ID ':' declaration=DataTypeDeclaration (':=' definition=GeneralExpression);
	public RoQMEGrammarAccess.GeneralPurposeVariableElements getGeneralPurposeVariableAccess() {
		return gaRoQME.getGeneralPurposeVariableAccess();
	}
	
	public ParserRule getGeneralPurposeVariableRule() {
		return getGeneralPurposeVariableAccess().getRule();
	}
	
	//Parameter kernel::Parameter:
	//	description=ElementDescription?
	//	'param' name=ID ':' declaration=DataTypeDeclaration ('default' initializedTo=TypedValue)?;
	public RoQMEGrammarAccess.ParameterElements getParameterAccess() {
		return gaRoQME.getParameterAccess();
	}
	
	public ParserRule getParameterRule() {
		return getParameterAccess().getRule();
	}
	
	//Timer kernel::Timer:
	//	'timer' name=ID declaration=InbuiltDeclaration (('offset' offset=TimeValue)?
	//	& once?='onetime'?
	//	& paused?='paused'?
	//	& ':=' definition=GeneralExpression);
	public RoQMEGrammarAccess.TimerElements getTimerAccess() {
		return gaRoQME.getTimerAccess();
	}
	
	public ParserRule getTimerRule() {
		return getTimerAccess().getRule();
	}
	
	//BeliefVariable kernel::BeliefVariable:
	//	BeliefVariableImpl | Property;
	public RoQMEGrammarAccess.BeliefVariableElements getBeliefVariableAccess() {
		return gaRoQME.getBeliefVariableAccess();
	}
	
	public ParserRule getBeliefVariableRule() {
		return getBeliefVariableAccess().getRule();
	}
	
	//BeliefVariableImpl kernel::BeliefVariable:
	//	description=ElementDescription?
	//	'beliefvar' name=ID declaration=InbuiltDeclaration (('reference' reference=EDouble)? & ('survival'
	//	survival=TimeValue)?);
	public RoQMEGrammarAccess.BeliefVariableImplElements getBeliefVariableImplAccess() {
		return gaRoQME.getBeliefVariableImplAccess();
	}
	
	public ParserRule getBeliefVariableImplRule() {
		return getBeliefVariableImplAccess().getRule();
	}
	
	//Property kernel::Property:
	//	description=ElementDescription?
	//	'property' name=ID (':' declaration=DataTypeDeclaration ':=' transformation=OutputTransformation |
	//	declaration=InbuiltDeclaration) (('reference' reference=EDouble)?
	//	& ('survival' survival=TimeValue)?);
	public RoQMEGrammarAccess.PropertyElements getPropertyAccess() {
		return gaRoQME.getPropertyAccess();
	}
	
	public ParserRule getPropertyRule() {
		return getPropertyAccess().getRule();
	}
	
	//Observation kernel::Observation:
	//	description=ElementDescription?
	//	'observation' name=ID ':' pattern=ContextPattern (actions+=Action | '{' actions+=Action+ '}');
	public RoQMEGrammarAccess.ObservationElements getObservationAccess() {
		return gaRoQME.getObservationAccess();
	}
	
	public ParserRule getObservationRule() {
		return getObservationAccess().getRule();
	}
	
	//Action kernel::Action:
	//	SetVariable | ClearEvidence | SetEvidence | TimerAction;
	public RoQMEGrammarAccess.ActionElements getActionAccess() {
		return gaRoQME.getActionAccess();
	}
	
	public ParserRule getActionRule() {
		return getActionAccess().getRule();
	}
	
	//TimerAction kernel::TimerAction:
	//	StartTimer | StopTimer | ResumeTimer;
	public RoQMEGrammarAccess.TimerActionElements getTimerActionAccess() {
		return gaRoQME.getTimerActionAccess();
	}
	
	public ParserRule getTimerActionRule() {
		return getTimerActionAccess().getRule();
	}
	
	//SetVariable kernel::SetVariable:
	//	'sets' variable=[datatypes::TypedVariable|QualifiedName]
	//	':=' expression=GeneralExpression;
	public RoQMEGrammarAccess.SetVariableElements getSetVariableAccess() {
		return gaRoQME.getSetVariableAccess();
	}
	
	public ParserRule getSetVariableRule() {
		return getSetVariableAccess().getRule();
	}
	
	//ClearEvidence kernel::ClearEvidence:
	//	'clears' target=[kernel::BeliefVariable|QualifiedName];
	public RoQMEGrammarAccess.ClearEvidenceElements getClearEvidenceAccess() {
		return gaRoQME.getClearEvidenceAccess();
	}
	
	public ParserRule getClearEvidenceRule() {
		return getClearEvidenceAccess().getRule();
	}
	
	//SetEvidence kernel::SetEvidence:
	//	influence=InfluenceEnum
	//	target=[kernel::BeliefVariable|QualifiedName] (strength=StrengthEnum? & ('survival' survival=TimeValue)?);
	public RoQMEGrammarAccess.SetEvidenceElements getSetEvidenceAccess() {
		return gaRoQME.getSetEvidenceAccess();
	}
	
	public ParserRule getSetEvidenceRule() {
		return getSetEvidenceAccess().getRule();
	}
	
	//enum InfluenceEnum returns kernel::InfluenceEnum:
	//	REINFORCE='reinforces' | UNDERMINE='undermines';
	public RoQMEGrammarAccess.InfluenceEnumElements getInfluenceEnumAccess() {
		return gaRoQME.getInfluenceEnumAccess();
	}
	
	public EnumRule getInfluenceEnumRule() {
		return getInfluenceEnumAccess().getRule();
	}
	
	//enum StrengthEnum returns kernel::StrengthEnum:
	//	VERY_HIGH='veryhigh' | HIGH='high' | MEDIUM | LOW='low' | VERY_LOW='verylow';
	public RoQMEGrammarAccess.StrengthEnumElements getStrengthEnumAccess() {
		return gaRoQME.getStrengthEnumAccess();
	}
	
	public EnumRule getStrengthEnumRule() {
		return getStrengthEnumAccess().getRule();
	}
	
	//StartTimer kernel::StartTimer:
	//	'starts' timer=[kernel::Timer|QualifiedName];
	public RoQMEGrammarAccess.StartTimerElements getStartTimerAccess() {
		return gaRoQME.getStartTimerAccess();
	}
	
	public ParserRule getStartTimerRule() {
		return getStartTimerAccess().getRule();
	}
	
	//StopTimer kernel::StopTimer:
	//	'stops' timer=[kernel::Timer|QualifiedName];
	public RoQMEGrammarAccess.StopTimerElements getStopTimerAccess() {
		return gaRoQME.getStopTimerAccess();
	}
	
	public ParserRule getStopTimerRule() {
		return getStopTimerAccess().getRule();
	}
	
	//ResumeTimer kernel::ResumeTimer:
	//	'resumes' timer=[kernel::Timer|QualifiedName];
	public RoQMEGrammarAccess.ResumeTimerElements getResumeTimerAccess() {
		return gaRoQME.getResumeTimerAccess();
	}
	
	public ParserRule getResumeTimerRule() {
		return getResumeTimerAccess().getRule();
	}
	
	///* *********************************
	// * DATATYPE EPACKAGE
	// * *********************************/ /* 
	// * Data type definitions
	// */ DataTypeDefinition datatypes::DataTypeDefinition:
	//	'type' name=EString ':' dataType=DataType;
	public RoQMEGrammarAccess.DataTypeDefinitionElements getDataTypeDefinitionAccess() {
		return gaRoQME.getDataTypeDefinitionAccess();
	}
	
	public ParserRule getDataTypeDefinitionRule() {
		return getDataTypeDefinitionAccess().getRule();
	}
	
	//DataType datatypes::DataType:
	//	BooleanType | super::EnumType | EventType | NumericType | UnitMeasuredType | TimeType;
	public RoQMEGrammarAccess.DataTypeElements getDataTypeAccess() {
		return gaRoQME.getDataTypeAccess();
	}
	
	public ParserRule getDataTypeRule() {
		return getDataTypeAccess().getRule();
	}
	
	//BooleanType datatypes::BooleanType:
	//	{datatypes::BooleanType}
	//	'boolean' ('[' cardinality=INT ']')?;
	public RoQMEGrammarAccess.BooleanTypeElements getBooleanTypeAccess() {
		return gaRoQME.getBooleanTypeAccess();
	}
	
	public ParserRule getBooleanTypeRule() {
		return getBooleanTypeAccess().getRule();
	}
	
	//EnumLiteral datatypes::EnumLiteral:
	//	{datatypes::EnumLiteral} name=ID;
	public RoQMEGrammarAccess.EnumLiteralElements getEnumLiteralAccess() {
		return gaRoQME.getEnumLiteralAccess();
	}
	
	public ParserRule getEnumLiteralRule() {
		return getEnumLiteralAccess().getRule();
	}
	
	//EventType datatypes::EventType:
	//	{datatypes::EventType}
	//	'eventtype' ('[' cardinality=INT ']')?;
	public RoQMEGrammarAccess.EventTypeElements getEventTypeAccess() {
		return gaRoQME.getEventTypeAccess();
	}
	
	public ParserRule getEventTypeRule() {
		return getEventTypeAccess().getRule();
	}
	
	//NumericType datatypes::NumericType:
	//	{datatypes::NumericType}
	//	'number' ('[' cardinality=INT ']')?
	//	constraints+=NumericTypeConstraint*;
	public RoQMEGrammarAccess.NumericTypeElements getNumericTypeAccess() {
		return gaRoQME.getNumericTypeAccess();
	}
	
	public ParserRule getNumericTypeRule() {
		return getNumericTypeAccess().getRule();
	}
	
	//NumericTypeConstraint datatypes::NumericTypeConstraint:
	//	LowerBound | UpperBound;
	public RoQMEGrammarAccess.NumericTypeConstraintElements getNumericTypeConstraintAccess() {
		return gaRoQME.getNumericTypeConstraintAccess();
	}
	
	public ParserRule getNumericTypeConstraintRule() {
		return getNumericTypeConstraintAccess().getRule();
	}
	
	//LowerBound datatypes::LowerBound:
	//	'lower' value=EDouble;
	public RoQMEGrammarAccess.LowerBoundElements getLowerBoundAccess() {
		return gaRoQME.getLowerBoundAccess();
	}
	
	public ParserRule getLowerBoundRule() {
		return getLowerBoundAccess().getRule();
	}
	
	//UpperBound datatypes::UpperBound:
	//	'upper' value=EDouble;
	public RoQMEGrammarAccess.UpperBoundElements getUpperBoundAccess() {
		return gaRoQME.getUpperBoundAccess();
	}
	
	public ParserRule getUpperBoundRule() {
		return getUpperBoundAccess().getRule();
	}
	
	//UnitMeasuredType datatypes::UnitMeasuredType:
	//	{datatypes::UnitMeasuredType}
	//	'number' ('[' cardinality=INT ']')?
	//	constraints+=NumericTypeConstraint*
	//	'unit' unit=EString
	//	constraints+=NumericTypeConstraint*;
	public RoQMEGrammarAccess.UnitMeasuredTypeElements getUnitMeasuredTypeAccess() {
		return gaRoQME.getUnitMeasuredTypeAccess();
	}
	
	public ParserRule getUnitMeasuredTypeRule() {
		return getUnitMeasuredTypeAccess().getRule();
	}
	
	//TimeType datatypes::TimeType:
	//	{datatypes::TimeType}
	//	'time' ('[' cardinality=INT ']')?;
	public RoQMEGrammarAccess.TimeTypeElements getTimeTypeAccess() {
		return gaRoQME.getTimeTypeAccess();
	}
	
	public ParserRule getTimeTypeRule() {
		return getTimeTypeAccess().getRule();
	}
	
	///*
	// * Typed Values
	// */ TypedValue datatypes::TypedValue:
	//	SingleValue | ArrayValue;
	public RoQMEGrammarAccess.TypedValueElements getTypedValueAccess() {
		return gaRoQME.getTypedValueAccess();
	}
	
	public ParserRule getTypedValueRule() {
		return getTypedValueAccess().getRule();
	}
	
	//SingleValue datatypes::SingleValue:
	//	BooleanValue | EnumValue | NumericValue | EventValue;
	public RoQMEGrammarAccess.SingleValueElements getSingleValueAccess() {
		return gaRoQME.getSingleValueAccess();
	}
	
	public ParserRule getSingleValueRule() {
		return getSingleValueAccess().getRule();
	}
	
	//EventValue datatypes::EventValue:
	//	{datatypes::EventValue}
	//	'event';
	public RoQMEGrammarAccess.EventValueElements getEventValueAccess() {
		return gaRoQME.getEventValueAccess();
	}
	
	public ParserRule getEventValueRule() {
		return getEventValueAccess().getRule();
	}
	
	//BooleanValue datatypes::BooleanValue:
	//	{datatypes::BooleanValue} value=EBoolean;
	public RoQMEGrammarAccess.BooleanValueElements getBooleanValueAccess() {
		return gaRoQME.getBooleanValueAccess();
	}
	
	public ParserRule getBooleanValueRule() {
		return getBooleanValueAccess().getRule();
	}
	
	//EnumValue datatypes::EnumValue:
	//	{datatypes::EnumValue} value=[datatypes::EnumLiteral|LiteralQualifiedName];
	public RoQMEGrammarAccess.EnumValueElements getEnumValueAccess() {
		return gaRoQME.getEnumValueAccess();
	}
	
	public ParserRule getEnumValueRule() {
		return getEnumValueAccess().getRule();
	}
	
	//NumericValue datatypes::NumericValue:
	//	NumericValue_Impl | UnitMeasuredValue;
	public RoQMEGrammarAccess.NumericValueElements getNumericValueAccess() {
		return gaRoQME.getNumericValueAccess();
	}
	
	public ParserRule getNumericValueRule() {
		return getNumericValueAccess().getRule();
	}
	
	//UnitMeasuredValue datatypes::UnitMeasuredValue:
	//	UnitMeasuredValue_Impl | TimeValue;
	public RoQMEGrammarAccess.UnitMeasuredValueElements getUnitMeasuredValueAccess() {
		return gaRoQME.getUnitMeasuredValueAccess();
	}
	
	public ParserRule getUnitMeasuredValueRule() {
		return getUnitMeasuredValueAccess().getRule();
	}
	
	//NumericValue_Impl datatypes::NumericValue:
	//	{datatypes::NumericValue} value=EDouble;
	public RoQMEGrammarAccess.NumericValue_ImplElements getNumericValue_ImplAccess() {
		return gaRoQME.getNumericValue_ImplAccess();
	}
	
	public ParserRule getNumericValue_ImplRule() {
		return getNumericValue_ImplAccess().getRule();
	}
	
	//UnitMeasuredValue_Impl datatypes::UnitMeasuredValue:
	//	{datatypes::UnitMeasuredValue} value=EDouble unit=EString;
	public RoQMEGrammarAccess.UnitMeasuredValue_ImplElements getUnitMeasuredValue_ImplAccess() {
		return gaRoQME.getUnitMeasuredValue_ImplAccess();
	}
	
	public ParserRule getUnitMeasuredValue_ImplRule() {
		return getUnitMeasuredValue_ImplAccess().getRule();
	}
	
	//TimeValue datatypes::TimeValue:
	//	{datatypes::TimeValue} value=EDouble unit=TimeUnitEnum;
	public RoQMEGrammarAccess.TimeValueElements getTimeValueAccess() {
		return gaRoQME.getTimeValueAccess();
	}
	
	public ParserRule getTimeValueRule() {
		return getTimeValueAccess().getRule();
	}
	
	//TimeUnitEnum:
	//	'milliseconds' | 'seconds' | 'minutes' | 'hours' | 'days'
	//	| 'millisecond' | 'second' | 'minute' | 'hour' | 'day';
	public RoQMEGrammarAccess.TimeUnitEnumElements getTimeUnitEnumAccess() {
		return gaRoQME.getTimeUnitEnumAccess();
	}
	
	public ParserRule getTimeUnitEnumRule() {
		return getTimeUnitEnumAccess().getRule();
	}
	
	//ArrayValue datatypes::ArrayValue:
	//	NumericArray | BooleanArray | EnumArray;
	public RoQMEGrammarAccess.ArrayValueElements getArrayValueAccess() {
		return gaRoQME.getArrayValueAccess();
	}
	
	public ParserRule getArrayValueRule() {
		return getArrayValueAccess().getRule();
	}
	
	//BooleanArray datatypes::ArrayValue:
	//	'[' values+=BooleanValue (',' values+=BooleanValue)* ']';
	public RoQMEGrammarAccess.BooleanArrayElements getBooleanArrayAccess() {
		return gaRoQME.getBooleanArrayAccess();
	}
	
	public ParserRule getBooleanArrayRule() {
		return getBooleanArrayAccess().getRule();
	}
	
	//EnumArray datatypes::ArrayValue:
	//	'[' values+=EnumValue (',' values+=EnumValue)* ']';
	public RoQMEGrammarAccess.EnumArrayElements getEnumArrayAccess() {
		return gaRoQME.getEnumArrayAccess();
	}
	
	public ParserRule getEnumArrayRule() {
		return getEnumArrayAccess().getRule();
	}
	
	//NumericArray datatypes::ArrayValue:
	//	NumericArray_Impl | UnitMeasuredArray;
	public RoQMEGrammarAccess.NumericArrayElements getNumericArrayAccess() {
		return gaRoQME.getNumericArrayAccess();
	}
	
	public ParserRule getNumericArrayRule() {
		return getNumericArrayAccess().getRule();
	}
	
	//UnitMeasuredArray datatypes::ArrayValue:
	//	UnitMeasuredArray_Impl | TimeArray;
	public RoQMEGrammarAccess.UnitMeasuredArrayElements getUnitMeasuredArrayAccess() {
		return gaRoQME.getUnitMeasuredArrayAccess();
	}
	
	public ParserRule getUnitMeasuredArrayRule() {
		return getUnitMeasuredArrayAccess().getRule();
	}
	
	//NumericArray_Impl datatypes::ArrayValue:
	//	'[' values+=NumericValue_Impl (',' values+=NumericValue_Impl)* ']';
	public RoQMEGrammarAccess.NumericArray_ImplElements getNumericArray_ImplAccess() {
		return gaRoQME.getNumericArray_ImplAccess();
	}
	
	public ParserRule getNumericArray_ImplRule() {
		return getNumericArray_ImplAccess().getRule();
	}
	
	//UnitMeasuredArray_Impl datatypes::ArrayValue:
	//	'[' values+=UnitMeasuredValue_Impl (',' values+=UnitMeasuredValue_Impl)* ']';
	public RoQMEGrammarAccess.UnitMeasuredArray_ImplElements getUnitMeasuredArray_ImplAccess() {
		return gaRoQME.getUnitMeasuredArray_ImplAccess();
	}
	
	public ParserRule getUnitMeasuredArray_ImplRule() {
		return getUnitMeasuredArray_ImplAccess().getRule();
	}
	
	//TimeArray datatypes::ArrayValue:
	//	'[' values+=TimeValue (',' values+=TimeValue)* ']';
	public RoQMEGrammarAccess.TimeArrayElements getTimeArrayAccess() {
		return gaRoQME.getTimeArrayAccess();
	}
	
	public ParserRule getTimeArrayRule() {
		return getTimeArrayAccess().getRule();
	}
	
	///*
	// * Typed Variables
	// */ DataTypeDeclaration datatypes::DataTypeDeclaration:
	//	InbuiltDeclaration | ReferencedDeclaration | ContainedDeclaration;
	public RoQMEGrammarAccess.DataTypeDeclarationElements getDataTypeDeclarationAccess() {
		return gaRoQME.getDataTypeDeclarationAccess();
	}
	
	public ParserRule getDataTypeDeclarationRule() {
		return getDataTypeDeclarationAccess().getRule();
	}
	
	//ContainedDeclaration datatypes::ContainedDeclaration:
	//	type=DataType;
	public RoQMEGrammarAccess.ContainedDeclarationElements getContainedDeclarationAccess() {
		return gaRoQME.getContainedDeclarationAccess();
	}
	
	public ParserRule getContainedDeclarationRule() {
		return getContainedDeclarationAccess().getRule();
	}
	
	//InbuiltDeclaration datatypes::InbuiltDeclaration:
	//	{datatypes::InbuiltDeclaration};
	public RoQMEGrammarAccess.InbuiltDeclarationElements getInbuiltDeclarationAccess() {
		return gaRoQME.getInbuiltDeclarationAccess();
	}
	
	public ParserRule getInbuiltDeclarationRule() {
		return getInbuiltDeclarationAccess().getRule();
	}
	
	//ReferencedDeclaration datatypes::ReferencedDeclaration:
	//	type=[datatypes::DataTypeDefinition];
	public RoQMEGrammarAccess.ReferencedDeclarationElements getReferencedDeclarationAccess() {
		return gaRoQME.getReferencedDeclarationAccess();
	}
	
	public ParserRule getReferencedDeclarationRule() {
		return getReferencedDeclarationAccess().getRule();
	}
	
	///* *********************************
	// * EXPRESSIONS EPACKAGE
	// * *********************************/ GeneralExpression expressions::GeneralExpression:
	//	term=Term;
	public RoQMEGrammarAccess.GeneralExpressionElements getGeneralExpressionAccess() {
		return gaRoQME.getGeneralExpressionAccess();
	}
	
	public ParserRule getGeneralExpressionRule() {
		return getGeneralExpressionAccess().getRule();
	}
	
	//OutputTransformation expressions::OutputTransformation:
	//	term=Term;
	public RoQMEGrammarAccess.OutputTransformationElements getOutputTransformationAccess() {
		return gaRoQME.getOutputTransformationAccess();
	}
	
	public ParserRule getOutputTransformationRule() {
		return getOutputTransformationAccess().getRule();
	}
	
	//ContextPattern expressions::ContextPattern:
	//	term=Term;
	public RoQMEGrammarAccess.ContextPatternElements getContextPatternAccess() {
		return gaRoQME.getContextPatternAccess();
	}
	
	public ParserRule getContextPatternRule() {
		return getContextPatternAccess().getRule();
	}
	
	//Term expressions::Term:
	//	OnceTerm | WhileTerm;
	public RoQMEGrammarAccess.TermElements getTermAccess() {
		return gaRoQME.getTermAccess();
	}
	
	public ParserRule getTermRule() {
		return getTermAccess().getRule();
	}
	
	///*
	// * Event Pattern Operators
	// */ //OnceTerm returns expressions::Term:
	////	WhileTerm
	////	('once' {expressions::OnceTerm.term=current})?;
	//OnceTerm expressions::OnceTerm:
	//	'once' term=WhileTerm;
	public RoQMEGrammarAccess.OnceTermElements getOnceTermAccess() {
		return gaRoQME.getOnceTermAccess();
	}
	
	public ParserRule getOnceTermRule() {
		return getOnceTermAccess().getRule();
	}
	
	//WhileTerm expressions::Term:
	//	RepetionTerm ({expressions::WhileTerm.left=current} 'while' '(' right=OrBooleanTerm ')')?;
	public RoQMEGrammarAccess.WhileTermElements getWhileTermAccess() {
		return gaRoQME.getWhileTermAccess();
	}
	
	public ParserRule getWhileTermRule() {
		return getWhileTermAccess().getRule();
	}
	
	//RepetionTerm expressions::Term:
	//	SequenceTerm ({expressions::RepeatTerm.term=current} 'repeat' '(' nrep=INT ')' | {expressions::RangeTerm.term=current}
	//	'range' '(' lowerBound=INT ',' upperBound=INT ')')?;
	public RoQMEGrammarAccess.RepetionTermElements getRepetionTermAccess() {
		return gaRoQME.getRepetionTermAccess();
	}
	
	public ParserRule getRepetionTermRule() {
		return getRepetionTermAccess().getRule();
	}
	
	//SequenceTerm expressions::Term:
	//	OrEventTerm ({expressions::FollowedByTerm.left=current} '->'
	//	right=ConditionalTerm)*;
	public RoQMEGrammarAccess.SequenceTermElements getSequenceTermAccess() {
		return gaRoQME.getSequenceTermAccess();
	}
	
	public ParserRule getSequenceTermRule() {
		return getSequenceTermAccess().getRule();
	}
	
	//OrEventTerm expressions::Term:
	//	AndEventTerm ({expressions::OrEventTerm.left=current} 'or' right=AndEventTerm)*;
	public RoQMEGrammarAccess.OrEventTermElements getOrEventTermAccess() {
		return gaRoQME.getOrEventTermAccess();
	}
	
	public ParserRule getOrEventTermRule() {
		return getOrEventTermAccess().getRule();
	}
	
	//AndEventTerm expressions::Term:
	//	(NotEventTerm | ConditionalTerm) ({expressions::AndEventTerm.left=current} 'and' right=(NotEventTerm |
	//	ConditionalTerm))*;
	public RoQMEGrammarAccess.AndEventTermElements getAndEventTermAccess() {
		return gaRoQME.getAndEventTermAccess();
	}
	
	public ParserRule getAndEventTermRule() {
		return getAndEventTermAccess().getRule();
	}
	
	//NotEventTerm expressions::Term:
	//	{expressions::NotEventTerm}
	//	'not' term=ConditionalTerm;
	public RoQMEGrammarAccess.NotEventTermElements getNotEventTermAccess() {
		return gaRoQME.getNotEventTermAccess();
	}
	
	public ParserRule getNotEventTermRule() {
		return getNotEventTermAccess().getRule();
	}
	
	///*
	// * Conditional Operator 
	// */ ConditionalTerm expressions::Term:
	//	OrBooleanTerm ({expressions::ConditionalTerm.terms+=current} '?' terms+=OrBooleanTerm ':' terms+=ConditionalTerm)?;
	public RoQMEGrammarAccess.ConditionalTermElements getConditionalTermAccess() {
		return gaRoQME.getConditionalTermAccess();
	}
	
	public ParserRule getConditionalTermRule() {
		return getConditionalTermAccess().getRule();
	}
	
	///*
	// * Logical Terms
	// */ OrBooleanTerm expressions::Term:
	//	AndBooleanTerm ({expressions::OrBooleanTerm.left=current} '|' right=AndBooleanTerm)*;
	public RoQMEGrammarAccess.OrBooleanTermElements getOrBooleanTermAccess() {
		return gaRoQME.getOrBooleanTermAccess();
	}
	
	public ParserRule getOrBooleanTermRule() {
		return getOrBooleanTermAccess().getRule();
	}
	
	//AndBooleanTerm expressions::Term:
	//	(NotBooleanTerm | RelationalTerm) ({expressions::AndBooleanTerm.left=current} '&' right=(NotBooleanTerm |
	//	RelationalTerm))*;
	public RoQMEGrammarAccess.AndBooleanTermElements getAndBooleanTermAccess() {
		return gaRoQME.getAndBooleanTermAccess();
	}
	
	public ParserRule getAndBooleanTermRule() {
		return getAndBooleanTermAccess().getRule();
	}
	
	//NotBooleanTerm expressions::Term:
	//	{expressions::NotBooleanTerm}
	//	'!' term=RelationalTerm;
	public RoQMEGrammarAccess.NotBooleanTermElements getNotBooleanTermAccess() {
		return gaRoQME.getNotBooleanTermAccess();
	}
	
	public ParserRule getNotBooleanTermRule() {
		return getNotBooleanTermAccess().getRule();
	}
	
	///*
	// * Relational Term
	// */ RelationalTerm expressions::Term:
	//	AdditionTerm (({expressions::EqualTerm.left=current} '='
	//	| {expressions::LessThanTerm.left=current} '<'
	//	| {expressions::GreaterThanTerm.left=current} '>'
	//	| {expressions::LessEqualTerm.left=current} '<='
	//	| {expressions::GreaterEqualTerm.left=current} '>='
	//	| {expressions::NotEqualTerm.left=current} '!=') right=AdditionTerm)?;
	public RoQMEGrammarAccess.RelationalTermElements getRelationalTermAccess() {
		return gaRoQME.getRelationalTermAccess();
	}
	
	public ParserRule getRelationalTermRule() {
		return getRelationalTermAccess().getRule();
	}
	
	///*
	// * Arithmetic Terms
	// */ AdditionTerm expressions::Term:
	//	MultiplicationTerm (({expressions::AddTerm.left=current} '+' | {expressions::SubTerm.left=current} '-')
	//	right=MultiplicationTerm)*;
	public RoQMEGrammarAccess.AdditionTermElements getAdditionTermAccess() {
		return gaRoQME.getAdditionTermAccess();
	}
	
	public ParserRule getAdditionTermRule() {
		return getAdditionTermAccess().getRule();
	}
	
	//MultiplicationTerm expressions::Term:
	//	PrimaryTerm (({expressions::MultTerm.left=current} '*' | {expressions::DivTerm.left=current} '/') right=PrimaryTerm)*;
	public RoQMEGrammarAccess.MultiplicationTermElements getMultiplicationTermAccess() {
		return gaRoQME.getMultiplicationTermAccess();
	}
	
	public ParserRule getMultiplicationTermRule() {
		return getMultiplicationTermAccess().getRule();
	}
	
	///*
	// * Primary Terms
	// */ PrimaryTerm expressions::Term:
	//	'(' Term ')' | ConstTerm | VarTerm | SelfTerm | FunctionTerm;
	public RoQMEGrammarAccess.PrimaryTermElements getPrimaryTermAccess() {
		return gaRoQME.getPrimaryTermAccess();
	}
	
	public ParserRule getPrimaryTermRule() {
		return getPrimaryTermAccess().getRule();
	}
	
	//VarTerm expressions::VarTerm:
	//	variable=[datatypes::TypedVariable|QualifiedName];
	public RoQMEGrammarAccess.VarTermElements getVarTermAccess() {
		return gaRoQME.getVarTermAccess();
	}
	
	public ParserRule getVarTermRule() {
		return getVarTermAccess().getRule();
	}
	
	//ConstTerm expressions::ConstTerm:
	//	value=TypedValue;
	public RoQMEGrammarAccess.ConstTermElements getConstTermAccess() {
		return gaRoQME.getConstTermAccess();
	}
	
	public ParserRule getConstTermRule() {
		return getConstTermAccess().getRule();
	}
	
	//SelfTerm expressions::SelfTerm:
	//	{expressions::SelfTerm}
	//	'belief';
	public RoQMEGrammarAccess.SelfTermElements getSelfTermAccess() {
		return gaRoQME.getSelfTermAccess();
	}
	
	public ParserRule getSelfTermRule() {
		return getSelfTermAccess().getRule();
	}
	
	///* 
	// * Functions
	// */ FunctionTerm expressions::FunctionTerm:
	//	ArithFunction | AggregationFunction | PatternFunction | CollectionFunction | ScheduleFunction;
	public RoQMEGrammarAccess.FunctionTermElements getFunctionTermAccess() {
		return gaRoQME.getFunctionTermAccess();
	}
	
	public ParserRule getFunctionTermRule() {
		return getFunctionTermAccess().getRule();
	}
	
	//ScheduleFunction expressions::ScheduleFunction:
	//	{expressions::ScheduleFunction}
	//	'schedule' '(' pattern=EString ')';
	public RoQMEGrammarAccess.ScheduleFunctionElements getScheduleFunctionAccess() {
		return gaRoQME.getScheduleFunctionAccess();
	}
	
	public ParserRule getScheduleFunctionRule() {
		return getScheduleFunctionAccess().getRule();
	}
	
	//ArithFunction expressions::ArithFunction:
	//	(terms+=(VarTerm | SelfTerm) "'")? name=ArithFtnEnum ('(' (terms+=Term (',' terms+=Term)*)? ')')?;
	public RoQMEGrammarAccess.ArithFunctionElements getArithFunctionAccess() {
		return gaRoQME.getArithFunctionAccess();
	}
	
	public ParserRule getArithFunctionRule() {
		return getArithFunctionAccess().getRule();
	}
	
	//enum ArithFtnEnum returns expressions::ArithFtnEnum:
	//	POW='pow' | SQRT='sqrt' | EXP='exp' | ABS='abs';
	public RoQMEGrammarAccess.ArithFtnEnumElements getArithFtnEnumAccess() {
		return gaRoQME.getArithFtnEnumAccess();
	}
	
	public EnumRule getArithFtnEnumRule() {
		return getArithFtnEnumAccess().getRule();
	}
	
	//AggregationFunction expressions::AggregationFunction:
	//	(terms+=(VarTerm | SelfTerm) "'")? name=AggregationFtnEnum ('(' (terms+=Term (',' terms+=Term)*)? ')')?;
	public RoQMEGrammarAccess.AggregationFunctionElements getAggregationFunctionAccess() {
		return gaRoQME.getAggregationFunctionAccess();
	}
	
	public ParserRule getAggregationFunctionRule() {
		return getAggregationFunctionAccess().getRule();
	}
	
	//enum AggregationFtnEnum returns expressions::AggregationFtnEnum:
	//	AVG='avg' | MIN='min' | MAX='max' | COUNT='count' | SUM='sum' | DECREASING='decreasing' | INCREASING='increasing' |
	//	STABLE='stable';
	public RoQMEGrammarAccess.AggregationFtnEnumElements getAggregationFtnEnumAccess() {
		return gaRoQME.getAggregationFtnEnumAccess();
	}
	
	public EnumRule getAggregationFtnEnumRule() {
		return getAggregationFtnEnumAccess().getRule();
	}
	
	//PatternFunction expressions::PatternFunction:
	//	(terms+=(VarTerm | SelfTerm) "'")? name=PatternFtnEnum ('(' (terms+=Term (',' terms+=Term)*)? ')')?;
	public RoQMEGrammarAccess.PatternFunctionElements getPatternFunctionAccess() {
		return gaRoQME.getPatternFunctionAccess();
	}
	
	public ParserRule getPatternFunctionRule() {
		return getPatternFunctionAccess().getRule();
	}
	
	//enum PatternFtnEnum returns expressions::PatternFtnEnum:
	//	EVENT_WHEN='eventWhen' | UPDATE='update' | PERIOD='period';
	public RoQMEGrammarAccess.PatternFtnEnumElements getPatternFtnEnumAccess() {
		return gaRoQME.getPatternFtnEnumAccess();
	}
	
	public EnumRule getPatternFtnEnumRule() {
		return getPatternFtnEnumAccess().getRule();
	}
	
	//CollectionFunction expressions::CollectionFunction:
	//	(terms+=(VarTerm | SelfTerm) "'")? name=CollectionFtnEnum ('(' (terms+=Term (',' terms+=Term)*)? ')')?;
	public RoQMEGrammarAccess.CollectionFunctionElements getCollectionFunctionAccess() {
		return gaRoQME.getCollectionFunctionAccess();
	}
	
	public ParserRule getCollectionFunctionRule() {
		return getCollectionFunctionAccess().getRule();
	}
	
	//enum CollectionFtnEnum returns expressions::CollectionFtnEnum:
	//	FIRST='first' | LAST='last' | AT='at' | SIZE='size' | IS_EMPTY='isEmpty' | INCLUDES='includes';
	public RoQMEGrammarAccess.CollectionFtnEnumElements getCollectionFtnEnumAccess() {
		return gaRoQME.getCollectionFtnEnumAccess();
	}
	
	public EnumRule getCollectionFtnEnumRule() {
		return getCollectionFtnEnumAccess().getRule();
	}
	
	///* *********************************
	// * Auxiliary grammar
	// * *********************************/ EString:
	//	STRING | ID;
	public RoQMEGrammarAccess.EStringElements getEStringAccess() {
		return gaRoQME.getEStringAccess();
	}
	
	public ParserRule getEStringRule() {
		return getEStringAccess().getRule();
	}
	
	//EDouble ecore::EDouble:
	//	'-'? INT ('.' INT)?;
	public RoQMEGrammarAccess.EDoubleElements getEDoubleAccess() {
		return gaRoQME.getEDoubleAccess();
	}
	
	public ParserRule getEDoubleRule() {
		return getEDoubleAccess().getRule();
	}
	
	////'-'? INT? '.' INT (('E'|'e') '-'? INT)?;
	//EBoolean ecore::EBoolean:
	//	'true' | 'false';
	public RoQMEGrammarAccess.EBooleanElements getEBooleanAccess() {
		return gaRoQME.getEBooleanAccess();
	}
	
	public ParserRule getEBooleanRule() {
		return getEBooleanAccess().getRule();
	}
	
	//QualifiedName:
	//	ID ('.' ID)*;
	public RoQMEGrammarAccess.QualifiedNameElements getQualifiedNameAccess() {
		return gaRoQME.getQualifiedNameAccess();
	}
	
	public ParserRule getQualifiedNameRule() {
		return getQualifiedNameAccess().getRule();
	}
	
	//LiteralQualifiedName:
	//	ID ('::' ID)+;
	public RoQMEGrammarAccess.LiteralQualifiedNameElements getLiteralQualifiedNameAccess() {
		return gaRoQME.getLiteralQualifiedNameAccess();
	}
	
	public ParserRule getLiteralQualifiedNameRule() {
		return getLiteralQualifiedNameAccess().getRule();
	}
	
	//ElementDescription:
	//	ROQME_DESCRIPTION;
	public RoQMEGrammarAccess.ElementDescriptionElements getElementDescriptionAccess() {
		return gaRoQME.getElementDescriptionAccess();
	}
	
	public ParserRule getElementDescriptionRule() {
		return getElementDescriptionAccess().getRule();
	}
	
	//terminal ROQME_DESCRIPTION:
	//	'/**'->'*/';
	public TerminalRule getROQME_DESCRIPTIONRule() {
		return gaRoQME.getROQME_DESCRIPTIONRule();
	}
	
	//@ Override terminal ML_COMMENT:
	//	('/*' !'*')->'*/';
	public TerminalRule getML_COMMENTRule() {
		return gaRoQME.getML_COMMENTRule();
	}
	
	//@ Override terminal STRING:
	//	'"' ('\\' ('b' | 't' | 'n' | 'f' | 'r' | 'u' | '"' | "'" | '\\') | !('\\' | '"'))* '"';
	public TerminalRule getSTRINGRule() {
		return gaRoQME.getSTRINGRule();
	}
	
	//terminal ID:
	//	'^'? ('a'..'z' | 'A'..'Z' | '_') ('a'..'z' | 'A'..'Z' | '_' | '0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt:
	//	'0'..'9'+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal SL_COMMENT:
	//	'//' !('\n' | '\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS:
	//	' ' | '\t' | '\r' | '\n'+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
