/**
 * generated by Xtext 2.12.0
 */
package org.xtext.miron.ui.quickfix;

import org.xtext.roqme.ui.quickfix.RoQMEQuickfixProvider;

/**
 * Custom quickfixes.
 * 
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#quick-fixes
 */
@SuppressWarnings("all")
public class MIRoNQuickfixProvider extends RoQMEQuickfixProvider {
}
