/**
 * generated by Xtext 2.12.0
 */
package org.xtext.behaviortree.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.xtext.behaviortree.BehaviorTreeRuntimeModule;
import org.xtext.behaviortree.BehaviorTreeStandaloneSetup;
import org.xtext.behaviortree.ide.BehaviorTreeIdeModule;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class BehaviorTreeIdeSetup extends BehaviorTreeStandaloneSetup {
  @Override
  public Injector createInjector() {
    BehaviorTreeRuntimeModule _behaviorTreeRuntimeModule = new BehaviorTreeRuntimeModule();
    BehaviorTreeIdeModule _behaviorTreeIdeModule = new BehaviorTreeIdeModule();
    return Guice.createInjector(Modules2.mixin(_behaviorTreeRuntimeModule, _behaviorTreeIdeModule));
  }
}
