/**
 * generated by Xtext 2.12.0
 */
package org.xtext.behaviortree.ide;

import org.xtext.behaviortree.ide.AbstractBehaviorTreeIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class BehaviorTreeIdeModule extends AbstractBehaviorTreeIdeModule {
}
