/**
 * generated by Xtext 2.12.0
 */
package org.xtext.behaviortree;

import org.xtext.behaviortree.BehaviorTreeStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class BehaviorTreeStandaloneSetup extends BehaviorTreeStandaloneSetupGenerated {
  public static void doSetup() {
    new BehaviorTreeStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
