/**
 * generated by Xtext 2.12.0
 */
package org.xtext.miron.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.xtext.miron.MIRoNRuntimeModule;
import org.xtext.miron.MIRoNStandaloneSetup;
import org.xtext.miron.ide.MIRoNIdeModule;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class MIRoNIdeSetup extends MIRoNStandaloneSetup {
  @Override
  public Injector createInjector() {
    MIRoNRuntimeModule _mIRoNRuntimeModule = new MIRoNRuntimeModule();
    MIRoNIdeModule _mIRoNIdeModule = new MIRoNIdeModule();
    return Guice.createInjector(Modules2.mixin(_mIRoNRuntimeModule, _mIRoNIdeModule));
  }
}
