/**
 * generated by Xtext 2.12.0
 */
package org.xtext.miron.ide;

import org.xtext.miron.ide.AbstractMIRoNIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class MIRoNIdeModule extends AbstractMIRoNIdeModule {
}
